### ISSUE TITLE
Invalid character in the docker tag since the new stable image versions 1.9.*

### ISSUE THREAD

**Issue by ggdaynight** [hotio/jellyfin#17]
Dear hotio,

In the latest releases the docker tags cannot be referred, which includes the versions. 
Here is the output from docker pulling commands for 2 different stable versions:

 ```bash
> docker image pull hotio/jellyfin:release-10.9.2+ubu2204
invalid reference format
> docker image pull hotio/jellyfin:release-10.8.13-1
release-10.8.13-1: Pulling from hotio/jellyfin
Digest: sha256:eea6afed7c8f344ddb4c21dde96f75257cbc8f5e143fa9ef86a0149d500a3f1f
Status: Image is up to date for hotio/jellyfin:release-10.8.13-1
docker.io/hotio/jellyfin:release-10.8.13-1
```

According to docker documentation the plus sign in docker tags is not in the allowed characters:
After the image name, the optional TAG is a custom, human-readable manifest identifier that's typically a specific version or variant of an image. **The tag must be valid ASCII and can contain lowercase and uppercase letters, digits, underscores, periods, and hyphens. It can't start with a period or hyphen and must be no longer than 128 characters**. If you don't specify a tag, the command uses latest by default.

Source:  https://docs.docker.com/reference/cli/docker/image/tag/#:~:text=After%20the%20image,by%20default.

Can you please change the plus sign in the docker tags to an other character, e.g. underscore?

Kind regards,
DayNight

**Comment by mrhotio** [comment]
Will do, thx for reporting
